import PortfolioEntry from "./PortfolioEntry";
import classes from "./Portfolio.module.scss";

const skills = {
  ReactJS: { name: "#ReactJS", color: "#61DAFB" },
  Firebase: { name: "#Firebase", color: "#FFCA28" },
  Database: { name: "#Database", color: "#FF7043" },
  CSS: { name: "#CSS", color: "#2965f1" },
  Sass: { name: "#Sass", color: "#CC6699" },
  Vite: { name: "#Vite", color: "#646CFF" },
  HTML: { name: "#HTML", color: "#E44D26" },
  JavaScript: { name: "#JavaScript", color: "#F7DF1E" },
  Desktop: { name: "#Desktop", color: "#fff" },
  Mobile: { name: "#Mobile", color: "#fff" },
  Animations: { name: "#Animations", color: "#fff" },
  API: { name: "#API", color: "#fff" },
};

export default function Portfolio() {
  return (
    <section className={classes.portfolio}>
      <h2>Personal Projects</h2>
      <p>
        Web applications developed from my own concepts to address challenges
        within personal commitments or everyday routines.
      </p>

      {/* 🎌 PAGE: Precision Gym */}
      <PortfolioEntry
        title="Gym Tracker App"
        links={{
          href: ["https://precision-gym.netlify.app/"],
          github: "https://github.com/Zluf/precision-gym-app-react",
        }}
        skills={[
          skills["ReactJS"],
          skills["Firebase"],
          skills["Database"],
          skills["CSS"],
        ]}
        img={{
          src: ["img/precision-gym.png"],
          alt: "screenshot precision-gym app",
        }}
        description="A front-end application enabling users to monitor their gym progress by entering pertinent data. Conceived during workout sessions, this app was developed to facilitate tracking and improvement."
        bulletpoints={[
          "User Input",
          "Data manipulation",
          "Storing and Fetching Database",
          "User Account Authentication",
        ]}
      />

      <h2>Custom Web Pages</h2>
      <p>
        Web applications and pages crafted using mock-ups and assets sourced
        from <a href="https://www.frontendmentor.io/">frontendmentor.io</a> to
        hone and enhance my skills through practice.
      </p>

      {/* 🎌 PAGE: Tic Tac Toe  */}
      <PortfolioEntry
        title="Tic Tac Toe"
        links={{
          href: ["https://tic-tac-toe-by-slavk.netlify.app/"],
          github: "https://github.com/Zluf/tic-tac-toe",
        }}
        skills={[
          skills["ReactJS"],
          skills["Vite"],
          skills["CSS"],
          skills["Animations"],
        ]}
        img={{
          src: ["img/tic-tac-toe.png"],
          alt: "screenshot tic tac toe game",
        }}
        description="Tic Tac Toe game built with ReactJS Functional Components with Vite build tool."
        bulletpoints={[
          "Animation sequences for Xs, Os and crossing out winning combination",
          "Score that gets updated",
          "Tie result",
          "Hover states for the current player's move",
          "Color harmony generated by Adobe Color Wheel",
        ]}
      />

      {/* 🎌 PAGE:E-Commerce  */}
      <PortfolioEntry
        title="E-Commerce Page"
        links={{
          href: ["/pages/e-commerce-page/"],
          github: "https://github.com/Zluf/e-commerce-app",
        }}
        skills={[
          skills["ReactJS"],
          skills["CSS"],
          skills["Desktop"],
          skills["Mobile"],
        ]}
        img={{
          src: ["img/e-commerce-page.png"],
          alt: "screenshot product page for an e-commerce company",
        }}
        description="E-Commerce product page built with ReactJS Functional
      Components."
        bulletpoints={[
          "Optimal layout for desktop, tablet and mobile devices",
          "Hover states for interactive elements on the page",
          "Clicking on the large product image opens a lightbox gallery",
          "Clicking on the small thumbnail images switches the largeproduct page",
          "Set product quantity can be added to the cart",
          "The cart can be viewed and emptied",
        ]}
      />

      {/* 🎌 PAGE: Advice Generator  */}
      <PortfolioEntry
        title="Advice Generator App"
        links={{
          href: ["/pages/advice-generator-app/"],
          github: "https://github.com/Zluf/advise-generator-app/",
        }}
        skills={[
          skills["HTML"],
          skills["CSS"],
          skills["JavaScript"],
          skills["API"],
          skills["Desktop"],
          skills["Mobile"],
        ]}
        img={{
          src: ["img/advice.png"],
          alt: "screenshot app that generates text from API",
        }}
        description="An app that generates random advice text from an external API."
        bulletpoints={[
          "Optimal layout for desktop and mobile devices",
          "Hover states for interactive elements on the page",
          "Clicking the button generates a new piece of advice",
        ]}
      />

      <h2>Private Tutoring Projects</h2>
      <p>
        Web pages created based on mock-ups and assets supplied by{" "}
        <a href="https://tomparson.com/">Tom Parson</a> during private tutoring
        sessions on Front End Development. These projects feature unique designs
        by <a href="https://www.huddledigital.com/">Huddle Digital</a> for
        real-life scenarios. To maintain confidentiality, any client names and
        specifics have been altered.
      </p>

      {/* 🎌 PAGE: Interior Design  */}
      <PortfolioEntry
        title="Interior Design Landing page"
        links={{
          href: ["/pages/interior/"],
          github: "https://github.com/Zluf/Interiors-page",
        }}
        skills={[
          skills["HTML"],
          skills["Sass"],
          skills["Desktop"],
          skills["Mobile"],
        ]}
        img={{
          src: ["img/interior.png"],
          alt: "screenshot landing page for an interior design service",
        }}
      />

      {/* 🎌 PAGE: Analytics  */}
      <PortfolioEntry
        title="Analytics page"
        links={{
          href: [
            "/pages/analytics/page1",
            "/pages/analytics/page2",
            "/pages/analytics/page3",
          ],
          github: "https://github.com/Zluf/Analytics-page",
        }}
        skills={[
          skills["HTML"],
          skills["CSS"],
          skills["Desktop"],
          skills["Mobile"],
        ]}
        img={{
          src: [
            "img/analytics-1.png",
            "img/analytics-2.png",
            "img/analytics-3.png",
          ],
          alt: "screenshot login page for an analytics service",
        }}
      />

      {/* 🎌 PAGE: Debt Solutions  */}
      <PortfolioEntry
        title="Debt Solutions page"
        links={{
          href: ["/pages/debt-solutions", "/pages/debt-solutions/page2"],
          github: "https://github.com/Zluf/Debt-Solutions-page",
        }}
        skills={[
          skills["HTML"],
          skills["CSS"],
          skills["Desktop"],
          skills["Mobile"],
        ]}
        img={{
          src: ["img/debt-1.png", "img/debt-2.png"],
          alt: "screenshot page for a debt solutions service",
        }}
      />

      {/* 🎌 PAGE: Charity  */}
      <PortfolioEntry
        title="Charity pages"
        links={{
          href: ["/pages/charity1/", "/pages/charity2/"],
          github: "https://github.com/Zluf/Charity-page-2",
        }}
        skills={[
          skills["HTML"],
          skills["CSS"],
          skills["Sass"],
          skills["JavaScript"],
        ]}
        img={{
          src: ["img/charity1.png", "img/charity2.png"],
          alt: "screenshot homepage for a charity",
        }}
      />
    </section>
  );
}
