import PortfolioEntry from "./PortfolioEntry";
import "../../styles/portfolio.scss";

export default function Portfolio() {
  return (
    <section className="portfolio" id="portfolio">
      <article className="portfolio__info">
        <h2>Portfolio</h2>
        <p>
          Here you can view the pages I've built, arranged most recent to
          oldest. All pages are built from scratch from pre-designed Adobe XD
          mock-ups.
        </p>
      </article>

      {/* 🎌 PAGE: Precision Gym */}
      <PortfolioEntry
        title="Gym Tracker App"
        links={{
          href: ["https://precision-gym.netlify.app/"],
          github: "https://github.com/Zluf/precision-gym-app-react",
        }}
        skills={["ReactJS", "Firebase", "Database", "CSS"]}
        img={{
          src: ["img/precision-gym.png"],
          alt: "screenshot precision-gym app",
        }}
        description="A Front End app that allows the user to track their gym progress by inputting relevant data. Built after an idea during workout sessions."
        bulletpoints={[
          "Own project",
          "User Input",
          "Data manipulation",
          "Storing and Fetching Database",
          "User Account Authentication",
        ]}
      />

      {/* 🎌 PAGE: Tic Tac Toe  */}
      <PortfolioEntry
        title="Tic Tac Toe"
        links={{
          href: ["https://tic-tac-toe-by-slavk.netlify.app/"],
          github: "https://github.com/Zluf/tic-tac-toe",
        }}
        skills={["ReactJS", "Vite", "CSS", "Animations"]}
        img={{
          src: ["img/tic-tac-toe.png"],
          alt: "screenshot tic tac toe game",
        }}
        description="A Front End app that allows the user to track their gym progress by inputting relevant data. Built after an idea during workout sessions."
        bulletpoints={[
          "Animation sequences for Xs, Os and crossing out winning combination",
          "Score that gets updated",
          "Tie result",
          "Hover states for the current player's move",
          "Color harmony generated by Adobe Color Wheel",
        ]}
      />

      {/* 🎌 PAGE:E-Commerce  */}
      <PortfolioEntry
        title="E-Commerce Page"
        links={{
          href: ["/pages/e-commerce-page/"],
          github: "https://github.com/Zluf/e-commerce-app",
        }}
        skills={["ReactJS", "CSS", "Desktop", "Mobile"]}
        img={{
          src: ["img/e-commerce-page.png"],
          alt: "screenshot product page for an e-commerce company",
        }}
        description="E-Commerce product page built with ReactJS Functional
            Components. Instructions, mock-up and assets are provided by
            Frontendmentor.io."
        bulletpoints={[
          "Optimal layout for desktop, tablet and mobile devices",
          "Hover states for interactive elements on the page",
          "Clicking on the large product image opens a lightbox gallery",
          "Clicking on the small thumbnail images switches the largeproduct page",
          "Set product quantity can be added to the cart",
          "The cart can be viewed and emptied",
        ]}
      />

      {/* 🎌 PAGE: Advice Generator  */}
      <PortfolioEntry
        title="Advice Generator App"
        links={{
          href: ["/pages/advice-generator-app/"],
          github: "https://github.com/Zluf/advise-generator-app/",
        }}
        skills={["HTML", "CSS", "JavaScript", "API", "Desktop", "Mobile"]}
        img={{
          src: ["img/advice.png"],
          alt: "screenshot app that generates text from API",
        }}
        description="An app that generates random advice text from an external API.
            Instructions, mock-up and assets are provided by
            Frontendmentor.io."
        bulletpoints={[
          "Optimal layout for desktop and mobile devices",
          "Hover states for interactive elements on the page",
          "Clicking the button generates a new piece of advice",
        ]}
      />

      {/* 🎌 PAGE: Interior Design  */}
      <PortfolioEntry
        title="Interior Design page"
        links={{
          href: ["/pages/interior/"],
          github: "https://github.com/Zluf/Interiors-page",
        }}
        skills={["HTML", "Sass", "Desktop", "Mobile"]}
        img={{
          src: ["img/interior.png"],
          alt: "screenshot landing page for an interior design service",
        }}
        description="Landing page for an interior design company. Built for
            HTML/CSS practice. Mock-up and Assets were provided by Tom
            Parson as part of his private tutoring. As page was designed
            for a client names and details are changed for
            confidentiality."
      />

      {/* 🎌 PAGE: Charity 2  */}
      <PortfolioEntry
        title="Charity page 2"
        links={{
          href: ["/pages/charity2/"],
          github: "https://github.com/Zluf/Charity-page-2",
        }}
        skills={["HTML", "Sass", "JavaScript", "Desktop"]}
        img={{
          src: ["img/charity2.png"],
          alt: "screenshot homepage for a charity",
        }}
        description="Built for HTML/CSS practice. Mock-up and Assets were provided
            by Tom Parson as part of his private tutoring. As page was
            designed for a client names and details are changed for
            confidentiality."
      />

      {/* 🎌 PAGE: Analytics  */}
      <PortfolioEntry
        title="Analytics page"
        links={{
          href: [
            "/pages/analytics/page1",
            "/pages/analytics/page2",
            "/pages/analytics/page3",
          ],
          github: "https://github.com/Zluf/Analytics-page",
        }}
        skills={["HTML", "CSS", "Desktop", " Mobile"]}
        img={{
          src: [
            "img/analytics-1.png",
            "img/analytics-2.png",
            "img/analytics-3.png",
          ],
          alt: "screenshot login page for an analytics service",
        }}
        description="Built for HTML/CSS practice. Mock-up and Assets were
            provided by Tom Parson as part of his private tutoring. As
            page was designed for a client names and details are
            changed for confidentiality."
      />

      {/* 🎌 PAGE: Sports Data  */}
      <PortfolioEntry
        title="Sports Data page"
        links={{
          href: ["/pages/sports-data/", "/pages/sports-data/page2"],
          github: "https://github.com/Zluf/Sports-data-page",
        }}
        skills={["HTML", "CSS", "Desktop"]}
        img={{
          src: ["img/sports-1.png", "img/sports-2.png"],
          alt: "screenshot a sports analytics page",
        }}
        description="Built for HTML/CSS practice. Mock-up and Assets were
            provided by Tom Parson as part of his private tutoring. As
            page was designed for a client names and details are
            changed for confidentiality."
      />

      {/* 🎌 PAGE: Debt Solutions  */}
      <PortfolioEntry
        title="Debt Solutions page"
        links={{
          href: ["/pages/debt-solutions", "/pages/debt-solutions/page2"],
          github: "https://github.com/Zluf/Debt-Solutions-page",
        }}
        skills={["HTML", "CSS", "Desktop", " Mobile"]}
        img={{
          src: ["img/debt-1.png", "img/debt-2.png"],
          alt: "screenshot page for a debt solutions service",
        }}
        description="Built for HTML/CSS practice. Mock-up and Assets were
            provided by Tom Parson as part of his private tutoring. As
            page was designed for a client names and details are
            changed for confidentiality."
      />

      {/* 🎌 PAGE: Charity 1  */}
      <PortfolioEntry
        title="Charity page 1"
        links={{
          href: ["/pages/charity1/"],
          github: "https://github.com/Zluf/Charity-page-1",
        }}
        skills={["HTML", "CSS", "Desktop"]}
        img={{
          src: ["img/charity1.png"],
          alt: "screenshot page for a charity organization",
        }}
        description="Built for HTML/CSS practice. Mock-up and Assets were
            provided by Tom Parson as part of his private tutoring. As
            page was designed for a client names and details are
            changed for confidentiality."
      />
    </section>
  );
}
